name: publish

on:
  push:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  IMAGE_NAME: goreney/ggab_api:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: |
        echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build and Publish Backend
      run: |
        docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  # deploy:
  #   needs: publish
  #   name: deploy image
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: install ssh keys
  #     # check this thread to understand why its needed:
  #     # <https://stackoverflow.com/a/70447517>
  #     run: |
  #       mkdir -p /home/runner/.ssh
  #       touch /home/runner/.ssh/goreney_lightsail.pem
  #       chmod 600 /home/runner/.ssh/goreney_lightsail.pem
  #       echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/goreney_lightsail.pem
  #       ssh-keyscan -H ${{ secrets.SSH_HOST }} > /home/runner/.ssh/known_hosts
  #   - name: connect and pull
  #     run: |
  #       echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  #       ssh -i /home/runner/.ssh/goreney_lightsail.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && sudo docker compose pull && sudo docker compose up -d && exit"
  #   - name: cleanup
  #     run: rm -rf /home/runner/.ssh